reconciliation_acceptance <- function() {
  fails <- function(expr, pattern = NULL) {
    error <- tryCatch(
      {
        force(expr)
        NULL
      },
      error = identity
    )
    stopifnot(inherits(error, 'error'))
    if (!is.null(pattern)) stopifnot(grepl(pattern, conditionMessage(error)))
  }
  operation <- function(service, required = FALSE) {
    list(
      service = service,
      key = 'GET /items',
      name = paste0(service, '_items'),
      path = '/items',
      method = 'GET',
      body = NULL,
      body_required = FALSE,
      parameters = list(list(
        name = 'limit',
        location = 'query',
        required = required,
        schema = list(type = 'integer')
      )),
      response = list()
    )
  }
  before <- list(operations = list(operation('first'), operation('second')))
  after <- list(
    operations = list(operation('first'), operation('second', TRUE))
  )
  delta <- apipak::compare_operations(before, after)
  stopifnot(length(delta) == 1L, delta[[1L]]$key == 'second GET /items')
  op <- operation('sample')
  op$name <- 'request_helper'
  fails(
    apipak::render_operation(op, list(helper = 'request_helper')),
    'collides'
  )
  hooks <- new.env(parent = baseenv())
  hooks$before <- function(state) state
  stopifnot(
    !apipak::validate_hooks(
      list(absent = list(pre_request = 'before')),
      list(),
      hooks
    )$valid
  )
  value <- getFromNamespace('fixture_value', 'apipak')
  stopifnot(is.null(value(
    list(type = 'string', nullable = TRUE, example = 'example'),
    NULL
  )))
  fails(value(list(type = 'string', example = 'example'), NULL), 'not nullable')
  stopifnot(
    identical(value(list(type = 'boolean'), FALSE), FALSE),
    value(list(type = 'integer'), 0) == 0
  )

  root <- tempfile('reconciliation-')
  dir.create(root)
  header <- '# Generated by wrapmaint; do not edit by hand.'
  original <- paste(header, 'example <- function() 1', sep = '\n')
  changed <- paste(header, 'example <- function() 2', sep = '\n')
  writeLines(original, file.path(root, 'legacy.R'))
  entries <- apipak::apply_files(root, list(legacy.R = changed), mode = 'plan')
  stopifnot(entries[[1L]]$action == 'protected')
  fails(
    apipak::apply_files(root, list(legacy.R = changed), mode = 'apply'),
    'Protected'
  )
  stopifnot(!dir.exists(file.path(root, '.apipak')))
  fails(
    apipak::apply_files(
      root,
      list(fresh.R = original),
      mode = 'apply',
      validate = function() {
        stopifnot(dir.exists(file.path(root, '.apipak-lock')))
        stop('Stale input')
      }
    ),
    'Stale input'
  )
  stopifnot(
    !file.exists(file.path(root, 'fresh.R')),
    !dir.exists(file.path(root, '.apipak-lock'))
  )
  apipak::apply_files(root, list(owned.R = original), mode = 'apply')
  writeLines(changed, file.path(root, 'owned.R'))
  stopifnot(
    apipak::apply_files(root, list(owned.R = original), mode = 'plan')[[
      1L
    ]]$action ==
      'protected'
  )
  writeLines(original, file.path(root, 'owned.R'))
  apipak::apply_files(root, list(owned.R = changed), mode = 'apply')
  hashes <- tools::md5sum(list.files(
    root,
    recursive = TRUE,
    all.files = TRUE,
    full.names = TRUE
  ))
  stopifnot(
    apipak::apply_files(root, list(owned.R = changed), mode = 'apply')[[
      1L
    ]]$action ==
      'unchanged'
  )
  stopifnot(identical(
    hashes,
    tools::md5sum(list.files(
      root,
      recursive = TRUE,
      all.files = TRUE,
      full.names = TRUE
    ))
  ))
  fails(
    apipak::apply_files(root, list('A.R' = original, 'a.R' = original)),
    'collide'
  )
  fails(apipak::apply_files(root, list('../escape.R' = original)), 'Unsafe')
  # Metadata-only drift must be visible without changing any project file.
  desired <- list(owned.R = changed)
  attr(desired, 'inputs') <- list('policy.yml' = 'reviewed-input-hash')
  before <- tools::md5sum(names(hashes))
  for (mode in c('plan', 'check')) {
    planned <- apipak::apply_files(root, desired, mode = mode)
    stopifnot(
      planned[[1L]]$action == 'unchanged',
      planned[[2L]]$file == '.apipak/manifest.json',
      planned[[2L]]$action == 'write',
      identical(before, tools::md5sum(names(hashes)))
    )
  }
  apipak::apply_files(root, desired, mode = 'apply')
  stopifnot(length(apipak::apply_files(root, desired, mode = 'check')) == 1L)
  # Shared-file owner arrays survive a later test-only publication unchanged.
  grouped <- list(
    grouped.R = 'first <- function() 1\nsecond <- function() 2',
    test.R = 'test <- TRUE'
  )
  attr(grouped, 'operations') <- list(
    grouped.R = c('service GET /first', 'service GET /second'),
    test.R = 'service GET /first'
  )
  apipak::apply_files(root, grouped, mode = 'apply')
  scoped <- grouped['test.R']
  attr(scoped, 'operations') <- attr(grouped, 'operations')['test.R']
  stopifnot(all(vapply(
    apipak::apply_files(root, scoped, mode = 'check'),
    function(x) x$action == 'unchanged',
    logical(1)
  )))
  journal <- file.path(root, '.wrapmaint-interrupted')
  dir.create(journal)
  saveRDS(list(), file.path(journal, 'recovery.rds'))
  fails(
    apipak::apply_files(root, list(fresh.R = original), mode = 'apply'),
    'recovery'
  )
  stopifnot(length(apipak::recover_client(root)) == 1L)
  apipak::recover_client(root, 'apply')
  stopifnot(!dir.exists(journal))

  # Fail at both outputs and the manifest; verify rollback and recovery.
  for (write in 1:3) {
    fault_root <- tempfile('fault-')
    dir.create(fault_root)
    apipak::apply_files(
      fault_root,
      list(one.R = original, two.R = original),
      mode = 'apply'
    )
    originals <- tools::md5sum(list.files(
      fault_root,
      recursive = TRUE,
      all.files = TRUE,
      full.names = TRUE
    ))
    context <- new.env(parent = asNamespace('apipak'))
    count <- 0L
    context$file.copy <- function(from, to, ...) {
      if (grepl('\\.new$', from)) {
        count <<- count + 1L
        if (count == write) return(FALSE)
      }
      base::file.copy(from, to, ...)
    }
    apply <- apipak::apply_files
    environment(apply) <- context
    fails(
      apply(fault_root, list(one.R = changed, two.R = changed), mode = 'apply'),
      'verify'
    )
    stopifnot(identical(
      unname(originals),
      unname(tools::md5sum(names(originals)))
    ))
    fails(apipak::apply_files(fault_root, list(), mode = 'apply'), 'recovery')
    apipak::recover_client(fault_root, 'apply')
    stopifnot(length(apipak::recover_client(fault_root)) == 0L)
  }
  # Hard termination cannot run on.exit(). Exercise the documented stale-lock path.
  worker <- callr::r_bg(
    function(root, changed) {
      context <- new.env(parent = asNamespace('apipak'))
      context$file.copy <- function(from, to, ...) {
        result <- base::file.copy(from, to, ...)
        if (grepl('\\.new$', from)) {
          writeLines('ready', file.path(root, 'interrupted'))
          Sys.sleep(60)
        }
        result
      }
      apply <- apipak::apply_files
      environment(apply) <- context
      apply(root, list(one.R = changed, two.R = changed), mode = 'apply')
    },
    args = list(fault_root, changed),
    libpath = .libPaths()
  )
  on.exit(if (worker$is_alive()) worker$kill(), add = TRUE)
  deadline <- Sys.time() + 20
  while (
    !file.exists(file.path(fault_root, 'interrupted')) &&
      worker$is_alive() &&
      Sys.time() < deadline
  ) {
    Sys.sleep(0.05)
  }
  stopifnot(file.exists(file.path(fault_root, 'interrupted')))
  worker$kill()
  worker$wait(5000)
  stopifnot(
    !worker$is_alive(),
    length(apipak::recover_client(fault_root)) == 1L
  )
  fails(apipak::recover_client(fault_root, 'apply'), 'lock exists')
  lock <- file.path(
    normalizePath(fault_root, winslash = '/', mustWork = TRUE),
    '.apipak-lock'
  )
  stopifnot(
    !fs::is_link(lock),
    length(list.files(lock, all.files = TRUE, no.. = TRUE)) == 0L
  )
  unlink(lock, recursive = TRUE)
  apipak::recover_client(fault_root, 'apply')
  stopifnot(identical(
    unname(originals),
    unname(tools::md5sum(names(originals)))
  ))
  cat(
    'Reconciliation: six audit contracts, conservative ownership, stale edits, containment, rollback and legacy recovery passed.\n'
  )
}
if (sys.nframe() == 0L) {
  reconciliation_acceptance()
}
