# Sourceable, offline probes for the pre-generalization implementation.
# FALSE means the proposed contract is not met; this is diagnostic evidence,
# not an acceptance suite that blesses existing behavior.
handoff_audit <- function(root = '.') {
  root <- normalizePath(root, winslash = '/', mustWork = TRUE)
  context <- new.env(parent = asNamespace('wrapmaint'))
  for (file in c('generation.R', 'operations.R', 'parameter_names.R',
                 'fixtures.R', 'hooks.R')) {
    sys.source(file.path(root, 'R', file), envir = context)
  }
  results <- list()
  record <- function(check, passed, observed) {
    results[[length(results) + 1L]] <<- data.frame(
      check = check, passed = isTRUE(passed), observed = observed
    )
  }

  operation <- function(service, required = FALSE) {
    list(key = 'GET /items', service = service, name = paste0(service, '_items'),
         method = 'GET', path = '/items', parameters = list(
           list(name = 'limit', location = 'query', required = required,
                schema = list(type = 'integer'))
         ), body = NULL, body_required = FALSE, response = list())
  }
  before <- list(operations = list(operation('first'), operation('second')))
  after <- list(operations = list(operation('first'), operation('second', TRUE)))
  changes <- context$compare_operations(before, after)
  record('Cross-service comparison detects second-service change',
         length(changes) > 0L, paste(length(changes), 'changes reported'))

  same_name <- operation('sample')
  same_name$name <- 'request_helper'
  runtime <- new.env(parent = baseenv())
  runtime$request_helper <- function(...) 'ok'
  source <- context$render_operation(same_name, list(helper = 'request_helper'))
  outcome <- tryCatch({
    eval(parse(text = source), envir = runtime)
    runtime$request_helper(limit = 1L)
  }, error = function(error) conditionMessage(error))
  record('Generated wrapper cannot collide with its request helper',
         identical(outcome, 'ok'), as.character(outcome))

  hooks <- new.env(parent = baseenv())
  hooks$before <- function(state) state
  hook_check <- context$validate_hooks(
    list(missing_wrapper = list(pre_request = 'before')), list(), hooks
  )
  record('Final hook check rejects a missing selected wrapper',
         !hook_check$valid, paste('valid =', hook_check$valid))

  fixture <- context$fixture_value(
    list(type = 'string', example = 'schema-example'), override = NULL
  )
  record('Fixture API distinguishes explicit null from absent override',
         is.null(fixture), paste('selected =', fixture))

  # Use only a newly created temporary root; never mutate the client checkout.
  temporary_root <- tempfile('apipak-handoff-audit-')
  dir.create(temporary_root)
  temporary_root <- normalizePath(temporary_root, winslash = '/', mustWork = TRUE)
  scratch_parent <- normalizePath(tempdir(), winslash = '/', mustWork = TRUE)
  stopifnot(startsWith(temporary_root, paste0(scratch_parent, '/')))
  on.exit(unlink(temporary_root, recursive = TRUE), add = TRUE)
  original <- paste('# Generated by wrapmaint; do not edit by hand.',
                    'audit_fn <- function() 1', sep = '\n')
  edited <- paste('# Generated by wrapmaint; do not edit by hand.',
                  'audit_fn <- function() 99', sep = '\n')
  output <- file.path(temporary_root, 'audit.R')
  writeLines(edited, output)
  actions <- context$apply_files(
    temporary_root, list(audit.R = original), mode = 'plan'
  )
  record('Generated header alone does not authorize replacing local edits',
         identical(actions[[1L]]$action, 'protected'),
         paste('planned action =', actions[[1L]]$action))

  # The current journal is not checked before planning a subsequent apply.
  journal <- file.path(temporary_root, '.wrapmaint-interrupted')
  dir.create(journal)
  saveRDS(list(), file.path(journal, 'recovery.rds'))
  recovery_rejected <- tryCatch({
    context$apply_files(temporary_root, list(audit.R = original), mode = 'apply')
    FALSE
  }, error = function(error) TRUE)
  record('Unresolved recovery journal prevents another apply',
         recovery_rejected, paste('rejected =', recovery_rejected))

  result <- do.call(rbind, results)
  attr(result, 'toolkit_version') <- as.character(utils::packageVersion('wrapmaint'))
  result
}

if (sys.nframe() == 0L) {
  audit <- handoff_audit()
  cat('Toolkit:', attr(audit, 'toolkit_version'), '\n', R.version.string, '\n')
  print(audit, row.names = FALSE)
}
