retire_legacy_tests <- function(root, apply = FALSE) {
  root <- normalizePath(root, winslash = '/', mustWork = TRUE)
  callbacks <- new.env(parent = baseenv())
  sys.source(file.path(root, 'dev/apipak_callbacks.R'), callbacks)
  operations <- apipak::inspect_client(root, callbacks = callbacks)$operations
  by_name <- stats::setNames(operations, vapply(operations, `[[`, character(1), 'name'))
  files <- list.files(file.path(root, 'tests/testthat'), '^test-.*\\.R$', full.names = TRUE)
  legacy <- files[vapply(files, function(path) any(head(readLines(path, warn = FALSE), 3L) %in% c(
    '# Generated by dev/generate_tests.R; do not edit by hand.',
    '# Generated using metadata-based test generator')), logical(1))]
  names <- sub('^test-(.*)[.]R$', '\\1', basename(legacy))
  manual <- names[!names %in% names(by_name)]
  if (length(manual)) cat('Legacy tests outside selected schemas:', paste(manual, collapse = ', '), '\n')
  baseline <- jsonlite::read_json('evidence/baseline/tracked-sha256.json')
  reviewed <- list()
  for (i in which(names %in% names(by_name))) {
    file <- substring(legacy[[i]], nchar(root) + 2L)
    operation <- by_name[[names[[i]]]]
    stopifnot(!is.null(operation$contract_file), operation$contract_file != file,
      !is.null(baseline[[file]]), identical(digest::digest(file = legacy[[i]], algo = 'sha256'), baseline[[file]]))
    reviewed[[file]] <- apipak:::output_hash(legacy[[i]])
  }
  records <- apipak::apply_files(root, list(), remove = names(reviewed), mode = if (apply) 'apply' else 'plan',
    owned = function(path) identical(apipak:::output_hash(path), reviewed[[substring(path, nchar(root) + 2L)]]))
  stopifnot(all(vapply(records, `[[`, character(1), 'action') == 'remove'))
  jsonlite::write_json(list(files = names(reviewed), hashes = reviewed, manual_retained = manual),
    'evidence/legacy-test-retirement.json', pretty = TRUE, auto_unbox = TRUE)
  cat(length(reviewed), 'reviewed legacy tests are replaced by fixed successful contracts.\n')
  invisible(records)
}
if (sys.nframe() == 0L) {
  args <- commandArgs(trailingOnly = TRUE)
  retire_legacy_tests(args[[1L]], '--apply' %in% args)
}
