# Generated by specmill; client-owned HTTP runtime.
api_request <- function(method, path, path_params, query, body) {
  for (name in names(path_params)) {
    path <- gsub(paste0('{', name, '}'), utils::URLencode(as.character(path_params[[name]]), reserved = TRUE), path, fixed = TRUE)
  }
  request <- httr2::request(BASE_URL)
  request <- httr2::req_method(request, method)
  query <- Filter(Negate(is.null), query)
  if (length(query)) request <- do.call(httr2::req_url_query, c(list(request), query))
  suffix <- if (grepl('?', request$url, fixed = TRUE)) sub('^[^?]*', '', request$url) else ''
  request <- httr2::req_url(request, paste0(sub('/+$', '', BASE_URL), '/', sub('^/+', '', path), suffix))
  if (!is.null(body)) request <- httr2::req_body_json(request, body, auto_unbox = TRUE, null = 'null')
  response <- httr2::req_perform(request)
  if (!httr2::resp_has_body(response)) return(NULL)
  bytes <- httr2::resp_body_raw(response)
  if (!length(bytes)) return(NULL)
  media <- httr2::resp_header(response, 'content-type')
  if (is.null(media)) media <- ''
  media <- tolower(sub(';.*$', '', media))
  if (grepl('(/json|\\+json)$', media)) return(httr2::resp_body_json(response, simplifyVector = FALSE))
  if (startsWith(media, 'text/') || media == 'image/svg+xml') return(httr2::resp_body_string(response))
  bytes
}
