# Generated by specmill; client-owned HTTP runtime.
api_request <- function(method, path, path_params, query, body, headers = list(), query_serialization = list(), body_media = 'application/json', auth = NULL, batch = list()) {
  for (limit in batch) {
    if (!is.numeric(limit) || length(limit) != 1L || is.na(limit) || !is.finite(limit) || limit < 1 || limit != floor(limit)) stop('Batch limits must be positive integers')
  }
  if (!is.null(batch$max_items) && !is.null(body)) {
    if (!is.list(body) || !is.null(names(body))) stop('Batch body must be an unnamed list of items')
    if (length(body) > batch$max_items) stop('Batch exceeds max_items (', batch$max_items, '); split the input into smaller requests')
  }
  for (name in names(path_params)) {
    path <- gsub(paste0('{', name, '}'), utils::URLencode(as.character(path_params[[name]]), reserved = TRUE), path, fixed = TRUE)
  }
  request <- httr2::request(BASE_URL)
  request <- httr2::req_method(request, method)
  query <- Filter(Negate(is.null), query)
  for (name in names(query)) {
    serialization <- query_serialization[[name]]
    if (is.null(serialization)) serialization <- 'error'
    if (name %in% names(query_serialization) && (!is.character(query[[name]]) || anyNA(query[[name]]))) stop('Query array must be a character vector without missing values')
    request <- do.call(httr2::req_url_query, c(list(request, .multi = serialization), query[name]))
  }
  headers <- Filter(Negate(is.null), headers)
  if (length(headers)) request <- do.call(httr2::req_headers, c(list(request), headers))
  suffix <- if (grepl('?', request$url, fixed = TRUE)) sub('^[^?]*', '', request$url) else ''
  request <- httr2::req_url(request, paste0(sub('/+$', '', BASE_URL), '/', sub('^/+', '', path), suffix))
  if (!is.null(body)) {
    if (!is.null(batch$max_bytes)) {
      bytes <- if (identical(body_media, 'application/json')) {
        charToRaw(enc2utf8(as.character(jsonlite::toJSON(body, auto_unbox = TRUE, null = 'null', digits = 22))))
      } else body
      if (!is.raw(bytes)) stop('Binary body must be a raw vector')
      if (length(bytes) > batch$max_bytes) stop('Batch exceeds max_bytes (', batch$max_bytes, ')')
      request <- httr2::req_body_raw(request, bytes, type = body_media)
    } else
    if (identical(body_media, 'application/octet-stream')) {
      if (!is.raw(body)) stop('Binary body must be a raw vector')
      request <- httr2::req_body_raw(request, body, type = body_media)
    } else if (identical(body_media, 'application/json')) {
      request <- httr2::req_body_json(request, body, auto_unbox = TRUE, null = 'null')
    } else stop('Unsupported request body media type')
  }
  if (!is.null(auth)) request <- api_auth(request, auth)
  response <- httr2::req_perform(request)
  if (!httr2::resp_has_body(response)) return(NULL)
  bytes <- httr2::resp_body_raw(response)
  if (!length(bytes)) return(NULL)
  media <- httr2::resp_header(response, 'content-type')
  if (is.null(media)) media <- ''
  media <- tolower(sub(';.*$', '', media))
  if (grepl('(/json|\\+json)$', media)) return(jsonlite::fromJSON(httr2::resp_body_string(response), simplifyVector = FALSE))
  if (startsWith(media, 'text/') || media == 'image/svg+xml') return(httr2::resp_body_string(response))
  bytes
}
