render_operation <- function(operation, spec) {
  helper <- spec$helper
  callback <- spec$hook_callback %or% 'run_hook'
  if (operation$name %in% c(helper, callback)) stop('Wrapper name collides with a helper or callback: ', operation$name)
  stopifnot(
    identical(make.names(helper), helper),
    identical(make.names(callback), callback)
  )
  params <- operation$parameters
  input_names <- vapply(params, `[[`, character(1), 'name')
  formal_names <- parameter_names(params)
  formal_names <- make.unique(c(
    formal_names,
    if (!is.null(operation$body)) 'body'
  ))
  mapping <- setNames(
    formal_names[seq_along(input_names)],
    vapply(params, function(p) paste(p$location, p$name), character(1))
  )
  signature <- vapply(
    seq_along(params),
    function(i) {
      paste0(
        formal_names[[i]],
        if (!isTRUE(params[[i]]$required)) ' = NULL' else ''
      )
    },
    character(1)
  )
  body_name <- if (!is.null(operation$body)) tail(formal_names, 1L) else NULL
  if (!is.null(body_name)) {
    signature <- c(
      signature,
      paste0(body_name, if (!operation$body_required) ' = NULL' else '')
    )
  }
  refs <- function(location) {
    selected <- Filter(function(p) p$location == location, params)
    paste0(
      'list(',
      paste(
        vapply(
          selected,
          function(p) {
            paste0(
              r_literal(p$name),
              ' = params[[',
              r_literal(mapping[[paste(p$location, p$name)]]),
              ']]'
            )
          },
          character(1)
        ),
        collapse = ', '
      ),
      ')'
    )
  }
  lines <- c(
    '# Generated by wrapmaint; do not edit by hand.',
    paste0(
      operation$name,
      ' <- function(',
      paste(signature, collapse = ', '),
      ') {'
    ),
    paste0(
      '  params <- list(',
      paste(
        vapply(
          formal_names,
          function(n) paste0(r_literal(n), ' = ', n),
          character(1)
        ),
        collapse = ', '
      ),
      ')'
    )
  )
  parameter_capture <- tail(lines, 1L)
  lines <- head(lines, -1L)
  for (i in seq_along(params)) {
    if (isTRUE(params[[i]]$required)) {
      lines <- c(
        lines,
        paste0(
          '  if (is.null(',
          formal_names[[i]],
          ')) stop(',
          r_literal(paste('Required input:', input_names[[i]])),
          ')'
        )
      )
    }
  }
  if (!is.null(body_name)) {
    if (operation$body_required) {
      lines <- c(
        lines,
        paste0('  if (is.null(', body_name, ')) stop("Required body")')
      )
    }
    required <- operation$body$required %or% character()
    lines <- c(
      lines,
      paste0(
        '  if (!is.null(',
        body_name,
        ') && (!is.list(',
        body_name,
        ') || !all(',
        r_literal(unlist(required)),
        ' %in% names(',
        body_name,
        ')))) stop("Missing required body fields")'
      )
    )
    if (
      identical(operation$body$type, 'array') &&
        identical(operation$body$items$type, 'object')
    ) {
      lines <- c(
        lines,
        paste0(
          '  if (!is.null(',
          body_name,
          ')) invisible(lapply(',
          body_name,
          ', function(.item) if (!is.list(.item) || !all(',
          r_literal(unlist(operation$body$items$required %or% character())),
          ' %in% names(.item))) stop("Missing required array item fields")))'
        )
      )
    }
  }
  lines <- c(lines, parameter_capture)
  hooks <- spec$hooks[[operation$name]] %or% list()
  if (length(hooks$pre_request)) {
    lines <- c(
      lines,
      paste0(
        '  state <- ',
        callback,
        '(',
        r_literal(operation$name),
        ', "pre_request", list(params = params))'
      ),
      '  if (isTRUE(state$skip_request)) return(state$result)',
      '  params <- state$params'
    )
  }
  lines <- c(
    lines,
    paste0(
      '  result <- ',
      helper,
      '(method = ',
      r_literal(operation$method),
      ', path = ',
      r_literal(operation$path),
      ', path_params = ',
      refs('path'),
      ', query = ',
      refs('query'),
      ', body = ',
      if (is.null(body_name)) {
        'NULL'
      } else {
        paste0('params[[', r_literal(body_name), ']]')
      },
      ')'
    )
  )
  if (length(hooks$post_response)) {
    lines <- c(
      lines,
      paste0(
        '  result <- ',
        callback,
        '(',
        r_literal(operation$name),
        ', "post_response", list(result = result, params = params))'
      )
    )
  }
  code <- paste(c(lines, '  result', '}'), collapse = '\n')
  if (isTRUE(spec$documentation)) paste(operation_documentation(operation), code, sep = '\n') else code
}

generate_client <- function(root, spec = NULL, mode = c('check', 'plan', 'apply'), config = NULL,
                            callbacks = new.env(parent = emptyenv())) {
  mode <- match.arg(mode)
  root <- normalizePath(root, winslash = '/', mustWork = TRUE)
  if (is.null(spec) == is.null(config)) stop('Supply exactly one of spec or config')
  if (!is.null(config)) {
    project <- load_project(root, config, callbacks)
    services <- project$services
    inputs <- project$inputs
  } else {
    if (!is.list(spec)) stop('spec must be a list')
    services <- list(spec)
    inputs <- spec$files
  }
  input_hashes <- vapply(inputs, function(x) digest::digest(file = x, algo = 'sha256'), character(1))
  parsed <- lapply(services, function(service) read_operations(service$files, service[['policy']] %or% list()))
  operations <- do.call(c, unname(lapply(parsed, `[[`, 'operations')))
  diagnostics <- do.call(c, unname(lapply(parsed, `[[`, 'diagnostics')))
  inventory <- do.call(c, unname(lapply(parsed, `[[`, 'inventory')))
  operation_names <- vapply(operations, `[[`, character(1), 'name')
  if (anyDuplicated(tolower(operation_names))) stop('Operation names collide across services (including case)')
  reserved <- unlist(lapply(services, function(x) c(x$helper, x$hook_callback %or% 'run_hook')), use.names = FALSE)
  if (any(operation_names %in% reserved)) stop('Wrapper name collides with a helper or callback')
  runtime_definitions <- list()
  for (file in list.files(file.path(root, 'R'), '\\.R$', full.names = TRUE)) {
    parse(file)
    definitions <- tg_find_function_defs_in_file(file)
    runtime_definitions <- c(runtime_definitions, definitions)
    collisions <- intersect(operation_names, names(definitions))
    if (length(collisions) && any(basename(file) != paste0(collisions, '.R'))) stop('Wrapper collides with an existing definition in ', file)
  }
  if (!is.null(config) && any(!reserved %in% c(names(runtime_definitions), 'run_hook'))) stop('Configured helper or callback has no client runtime definition')
  if (mode != 'plan' && length(diagnostics)) stop('Unsupported selected operations; inspect plan diagnostics before generation')
  desired <- list()
  owners <- list()
  for (i in seq_along(services)) {
    service <- services[[i]]
    renderer <- service$renderer %or% render_operation
    for (op in parsed[[i]]$operations) {
      if (!is.null(service$prepare)) {
        prepared <- service$prepare(op)
        if (!identical(prepared[c('id', 'name', 'service', 'key')], op[c('id', 'name', 'service', 'key')])) stop('Preparation callback must preserve operation identity and configured name')
        op <- prepared
      }
      desired[[paste0('R/', op$name, '.R')]] <- renderer(op, service)
      owners[[paste0('R/', op$name, '.R')]] <- op$id
      if (op$name %in% names(service$contracts)) {
        desired[[paste0('tests/testthat/test-', op$name, '.R')]] <- render_contract(op, service, service$contracts[[op$name]])
        owners[[paste0('tests/testthat/test-', op$name, '.R')]] <- op$id
      }
    }
  }
  if (!identical(input_hashes, vapply(inputs, function(x) digest::digest(file = x, algo = 'sha256'), character(1)))) stop('Stale input plan; schema or configuration changed during generation')
  attr(desired, 'operations') <- owners
  labels <- ifelse(startsWith(inputs, paste0(root, '/')), substring(inputs, nchar(root) + 2L), basename(inputs))
  attr(desired, 'inputs') <- as.list(stats::setNames(input_hashes, labels))
  removals <- character()
  manifest_path <- project_path(root, '.apipak/manifest.json')
  if (file.exists(manifest_path)) {
    previous <- jsonlite::read_json(manifest_path)$files
    excluded <- vapply(Filter(function(x) x$status == 'excluded', inventory), `[[`, character(1), 'id')
    removals <- names(Filter(function(x) length(x$operations) && all(unlist(x$operations) %in% excluded), previous))
    removals <- setdiff(removals, names(desired))
  }
  if (any(vapply(services, function(x) isTRUE(x$documentation), logical(1)))) desired <- document_output(root, desired, removals)
  if (any(vapply(services, function(x) length(x$hooks) > 0L, logical(1)))) {
    wrapper_functions <- lapply(runtime_definitions, function(x) eval(x$expr, baseenv()))
    for (name in names(desired)[grepl('\\.R$', names(desired))]) {
      for (expression in as.list(parse(text = desired[[name]]))) {
        if (is.call(expression) && identical(expression[[1L]], as.name('<-')) && is.symbol(expression[[2L]]) &&
            is.call(expression[[3L]]) && identical(expression[[3L]][[1L]], as.name('function'))) {
          wrapper_functions[[as.character(expression[[2L]])]] <- eval(expression[[3L]], baseenv())
        }
      }
    }
    hook_environment <- list2env(wrapper_functions, parent = emptyenv())
    for (service in services) {
      if (!length(service$hooks)) next
      validation <- validate_hooks(service$hooks, wrapper_functions, hook_environment, service$hook_callback %or% 'run_hook')
      if (!validation$valid) stop(paste(validation$errors, collapse = '\n'))
    }
  }
  # Unsupported operations never remove previous output or manual files.
  result <- apply_files(
    root,
    desired,
    remove = removals,
    mode = mode,
    headers = '# Generated by wrapmaint; do not edit by hand.'
  )
  if (mode == 'check' && any(vapply(result, function(x) !x$action %in% c('unchanged', 'retained'), logical(1)))) stop('Generated output is stale or protected; inspect plan')
  list(
    files = result,
    operations = operations,
    diagnostics = diagnostics,
    inventory = inventory,
    manifest = list(
      toolkit_version = as.character(utils::packageVersion('apipak')),
      inputs = input_hashes,
      policy_version = vapply(services, function(x) x$policy_version %or% 'unspecified', character(1))
    )
  )
}

# Fixed expectations are supplied by the client, independently of wrapper parsing.
check_requests <- function(call, expected, capture, result) {
  actual <- call()
  stopifnot(identical(capture(), expected), identical(actual, result))
  invisible(TRUE)
}
