render_operation <- function(operation, spec) {
  helper <- spec$helper
  callback <- spec$hook_callback %or% 'run_hook'
  stopifnot(
    identical(make.names(helper), helper),
    identical(make.names(callback), callback)
  )
  params <- operation$parameters
  input_names <- vapply(params, `[[`, character(1), 'name')
  formal_names <- parameter_names(params)
  formal_names <- make.unique(c(
    formal_names,
    if (!is.null(operation$body)) 'body'
  ))
  mapping <- setNames(
    formal_names[seq_along(input_names)],
    vapply(params, function(p) paste(p$location, p$name), character(1))
  )
  signature <- vapply(
    seq_along(params),
    function(i) {
      paste0(
        formal_names[[i]],
        if (!isTRUE(params[[i]]$required)) ' = NULL' else ''
      )
    },
    character(1)
  )
  body_name <- if (!is.null(operation$body)) tail(formal_names, 1L) else NULL
  if (!is.null(body_name)) {
    signature <- c(
      signature,
      paste0(body_name, if (!operation$body_required) ' = NULL' else '')
    )
  }
  refs <- function(location) {
    selected <- Filter(function(p) p$location == location, params)
    paste0(
      'list(',
      paste(
        vapply(
          selected,
          function(p) {
            paste0(
              r_literal(p$name),
              ' = params[[',
              r_literal(mapping[[paste(p$location, p$name)]]),
              ']]'
            )
          },
          character(1)
        ),
        collapse = ', '
      ),
      ')'
    )
  }
  lines <- c(
    '# Generated by wrapmaint; do not edit by hand.',
    paste0(
      operation$name,
      ' <- function(',
      paste(signature, collapse = ', '),
      ') {'
    ),
    paste0(
      '  params <- list(',
      paste(
        vapply(
          formal_names,
          function(n) paste0(r_literal(n), ' = ', n),
          character(1)
        ),
        collapse = ', '
      ),
      ')'
    )
  )
  parameter_capture <- tail(lines, 1L)
  lines <- head(lines, -1L)
  for (i in seq_along(params)) {
    if (isTRUE(params[[i]]$required)) {
      lines <- c(
        lines,
        paste0(
          '  if (is.null(',
          formal_names[[i]],
          ')) stop(',
          r_literal(paste('Required input:', input_names[[i]])),
          ')'
        )
      )
    }
  }
  if (!is.null(body_name)) {
    if (operation$body_required) {
      lines <- c(
        lines,
        paste0('  if (is.null(', body_name, ')) stop("Required body")')
      )
    }
    required <- operation$body$required %or% character()
    lines <- c(
      lines,
      paste0(
        '  if (!is.null(',
        body_name,
        ') && (!is.list(',
        body_name,
        ') || !all(',
        r_literal(unlist(required)),
        ' %in% names(',
        body_name,
        ')))) stop("Missing required body fields")'
      )
    )
    if (
      identical(operation$body$type, 'array') &&
        identical(operation$body$items$type, 'object')
    ) {
      lines <- c(
        lines,
        paste0(
          '  if (!is.null(',
          body_name,
          ')) invisible(lapply(',
          body_name,
          ', function(.item) if (!is.list(.item) || !all(',
          r_literal(unlist(operation$body$items$required %or% character())),
          ' %in% names(.item))) stop("Missing required array item fields")))'
        )
      )
    }
  }
  lines <- c(lines, parameter_capture)
  hooks <- spec$hooks[[operation$name]] %or% list()
  if (length(hooks$pre_request)) {
    lines <- c(
      lines,
      paste0(
        '  state <- ',
        callback,
        '(',
        r_literal(operation$name),
        ', "pre_request", list(params = params))'
      ),
      '  if (isTRUE(state$skip_request)) return(state$result)',
      '  params <- state$params'
    )
  }
  lines <- c(
    lines,
    paste0(
      '  result <- ',
      helper,
      '(method = ',
      r_literal(operation$method),
      ', path = ',
      r_literal(operation$path),
      ', path_params = ',
      refs('path'),
      ', query = ',
      refs('query'),
      ', body = ',
      if (is.null(body_name)) {
        'NULL'
      } else {
        paste0('params[[', r_literal(body_name), ']]')
      },
      ')'
    )
  )
  if (length(hooks$post_response)) {
    lines <- c(
      lines,
      paste0(
        '  result <- ',
        callback,
        '(',
        r_literal(operation$name),
        ', "post_response", list(result = result, params = params))'
      )
    )
  }
  paste(c(lines, '  result', '}'), collapse = '\n')
}

generate_client <- function(root, spec, mode = c('check', 'plan', 'apply')) {
  mode <- match.arg(mode)
  parsed <- read_operations(spec$files, spec[['policy']] %or% list())
  renderer <- spec$renderer %or% render_operation
  desired <- lapply(parsed$operations, function(op) renderer(op, spec))
  if (length(desired)) {
    names(desired) <- paste0('R/', names(parsed$operations), '.R')
  }
  for (name in names(spec$contracts)) {
    if (name %in% names(parsed$operations)) {
      desired[[paste0('tests/testthat/test-', name, '.R')]] <-
        render_contract(parsed$operations[[name]], spec, spec$contracts[[name]])
    }
  }
  # Unsupported operations never remove previous output or manual files.
  result <- apply_files(
    root,
    desired,
    mode = mode,
    headers = '# Generated by wrapmaint; do not edit by hand.'
  )
  list(
    files = result,
    operations = parsed$operations,
    diagnostics = parsed$diagnostics,
    manifest = list(
      toolkit_version = as.character(utils::packageVersion('apipak')),
      inputs = tools::md5sum(spec$files),
      policy_version = spec$policy_version %or% 'unspecified'
    )
  )
}

apply_files <- function(
  root,
  desired,
  remove = character(),
  mode = c('check', 'plan', 'apply'),
  headers = '# Generated by wrapmaint; do not edit by hand.',
  owned = NULL
) {
  mode <- match.arg(mode)
  root <- normalizePath(root, winslash = '/', mustWork = TRUE)
  safe_path <- function(relative) {
    if (
      !is.character(relative) ||
        length(relative) != 1L ||
        !nzchar(relative) ||
        grepl('(^[/\\\\]|^[A-Za-z]:|(^|[/\\\\])\\.\\.([/\\\\]|$))', relative)
    ) {
      stop('Path escapes target root: ', relative)
    }
    path <- file.path(root, relative)
    ancestor <- dirname(path)
    while (!dir.exists(ancestor)) {
      ancestor <- dirname(ancestor)
    }
    resolved <- normalizePath(ancestor, winslash = '/', mustWork = TRUE)
    if (
      resolved != root && !startsWith(paste0(resolved, '/'), paste0(root, '/'))
    ) {
      stop('Path escapes target root')
    }
    if (file.exists(path)) {
      resolved_file <- normalizePath(path, winslash = '/', mustWork = TRUE)
      if (!startsWith(resolved_file, paste0(root, '/'))) {
        stop('File escapes target root')
      }
    }
    path
  }
  if (
    length(desired) &&
      (is.null(names(desired)) || anyDuplicated(names(desired)))
  ) {
    stop('Output paths must be unique')
  }
  paths <- vapply(c(names(desired), remove), safe_path, character(1))
  targets <- as.character(fs::path_norm(paths))
  if (.Platform$OS.type == 'windows') {
    targets <- tolower(targets)
  }
  if (anyDuplicated(targets)) {
    stop('Output and removal paths must not overlap or repeat')
  }
  ownership <- owned %or%
    function(path) any(readLines(path, n = 5L, warn = FALSE) %in% headers)
  owned <- function(path) !file.exists(path) || isTRUE(ownership(path))
  # Parse all output before any filesystem mutation.
  for (name in names(desired)) {
    if (grepl('\\.R$', name)) parse(text = desired[[name]])
  }
  entries <- lapply(seq_along(paths), function(i) {
    path <- paths[[i]]
    name <- c(names(desired), remove)[[i]]
    action <- if (!owned(path)) {
      'protected'
    } else if (i > length(desired)) {
      'remove'
    } else if (
      file.exists(path) &&
        identical(
          paste(readLines(path, warn = FALSE), collapse = '\n'),
          desired[[name]]
        )
    ) {
      'unchanged'
    } else {
      'write'
    }
    list(file = name, path = path, action = action)
  })
  if (mode != 'apply') {
    return(entries)
  }
  pending <- Filter(function(e) e$action %in% c('write', 'remove'), entries)
  if (!length(pending)) {
    return(entries)
  }
  transaction <- tempfile('.wrapmaint-', tmpdir = root)
  dir.create(transaction)
  backup <- list()
  complete <- FALSE
  on.exit(
    {
      if (!complete) {
        for (entry in backup) {
          if (entry$existed) {
            file.copy(entry$backup, entry$path, overwrite = TRUE)
          } else if (file.exists(entry$path)) {
            unlink(entry$path)
          }
        }
      }
      if (complete) unlink(transaction, recursive = TRUE)
    },
    add = TRUE
  )
  for (i in seq_along(pending)) {
    e <- pending[[i]]
    copy <- file.path(transaction, paste0(i, '.backup'))
    existed <- file.exists(e$path)
    if (existed && !file.copy(e$path, copy)) {
      stop('Could not back up output')
    }
    backup[[i]] <- list(path = e$path, existed = existed, backup = copy)
    if (e$action == 'write') {
      writeLines(
        desired[[e$file]],
        file.path(transaction, paste0(i, '.new')),
        useBytes = TRUE
      )
    }
  }
  saveRDS(backup, file.path(transaction, 'recovery.rds'))
  for (i in seq_along(pending)) {
    e <- pending[[i]]
    if (e$action == 'remove') {
      if (unlink(e$path) != 0L) stop('Could not remove output')
    } else {
      dir.create(dirname(e$path), recursive = TRUE, showWarnings = FALSE)
      if (
        !file.copy(
          file.path(transaction, paste0(i, '.new')),
          e$path,
          overwrite = TRUE
        )
      ) {
        stop('Could not apply output')
      }
    }
  }
  complete <- TRUE
  entries
}

# Fixed expectations are supplied by the client, independently of wrapper parsing.
check_requests <- function(call, expected, capture, result) {
  actual <- call()
  stopifnot(identical(capture(), expected), identical(actual, result))
  invisible(TRUE)
}
