render_contract <- function(operation, spec, contract) {
  if ('calls' %in% names(contract)) {
    return(render_fixed_contract(operation, spec, contract))
  }
  if (
    !all(c('inputs', 'request', 'result') %in% names(contract)) ||
      !'response_fixture' %in% union(names(spec), names(contract))
  ) {
    stop('Supply fixed contract inputs, request, result and response_fixture')
  }
  stopifnot(identical(make.names(spec$package), spec$package))
  args <- paste(
    vapply(
      names(contract$inputs),
      function(name) {
        paste0(
          r_literal(make.names(name)),
          ' = ',
          r_literal(contract$inputs[[name]])
        )
      },
      character(1)
    ),
    collapse = ', '
  )
  paste(
    c(
      '# Generated by wrapmaint; do not edit by hand.',
      paste0(
        'testthat::test_that(',
        r_literal(paste(
          operation$name,
          'completes the fixed request contract'
        )),
        ', {'
      ),
      '  captured <- NULL',
      '  calls <- 0L',
      paste0(
        '  mock <- function(...) { calls <<- calls + 1L; captured <<- list(...); ',
        r_literal(
          if ('response_fixture' %in% names(contract)) {
            contract$response_fixture
          } else {
            spec$response_fixture
          }
        ),
        ' }'
      ),
      paste0(
        '  testthat::local_mocked_bindings(',
        spec$helper,
        ' = mock, .package = ',
        r_literal(spec$package),
        ')'
      ),
      paste0(
        '  result <- ',
        spec$package,
        '::',
        operation$name,
        '(',
        args,
        ')'
      ),
      paste0(
        '  testthat::expect_identical(captured, ',
        r_literal(contract$request),
        ')'
      ),
      '  testthat::expect_identical(calls, 1L)',
      paste0(
        '  testthat::expect_identical(result, ',
        r_literal(contract$result),
        ')'
      ),
      '})'
    ),
    collapse = '\n'
  )
}

validate_fixed_contract <- function(contract) {
  data_only <- function(x, depth = 0L) {
    if (
      depth > 100L ||
        !typeof(x) %in%
          c(
            'NULL',
            'logical',
            'integer',
            'double',
            'complex',
            'character',
            'raw',
            'list',
            'language',
            'symbol',
            'pairlist'
          )
    ) {
      stop('Contract fixtures must contain only R data')
    }
    if (is.list(x) || is.call(x) || is.pairlist(x)) {
      for (value in as.list(x)) {
        data_only(value, depth + 1L)
      }
    }
    for (value in attributes(x)) {
      data_only(value, depth + 1L)
    }
  }
  data_only(contract)
  config_fields(
    contract,
    c('inputs', 'calls', 'result', 'environment'),
    'fixed contract'
  )
  if (!is.null(contract$environment)) {
    config_fields(
      contract$environment,
      names(contract$environment),
      'contract environment'
    )
    for (value in contract$environment) {
      config_string(value, 'contract environment value')
    }
  }
  if (
    !all(c('inputs', 'calls', 'result') %in% names(contract)) ||
      !length(contract$calls)
  ) {
    stop('Fixed contract requires inputs, successful result and expected calls')
  }
  config_fields(contract$inputs, names(contract$inputs), 'contract inputs')
  for (call in contract$calls) {
    config_fields(call, c('helper', 'arguments', 'response'), 'contract call')
    if (!all(c('helper', 'arguments', 'response') %in% names(call))) {
      stop('Incomplete fixed call')
    }
    name <- config_string(call$helper, 'contract helper')
    if (!identical(make.names(name), name)) {
      stop('Invalid contract helper')
    }
    if (!is.list(call$arguments)) stop('Contract arguments must be a list')
  }
  invisible(contract)
}

render_fixed_contract <- function(operation, spec, contract) {
  validate_fixed_contract(contract)
  stopifnot(identical(make.names(spec$package), spec$package))
  if (is.null(spec$contracts_file)) {
    stop('Fixed call sequences require contracts_file')
  }
  helpers <- unique(vapply(contract$calls, `[[`, character(1), 'helper'))
  if (!spec$helper %in% helpers) {
    stop('Fixed contract must exercise its request helper')
  }
  paste(
    c(
      '# Generated by wrapmaint; do not edit by hand.',
      paste0(
        'testthat::test_that(',
        r_literal(paste(operation$name, 'completes the fixed call sequence')),
        ', {'
      ),
      paste0(
        '  contract <- readRDS(testthat::test_path(',
        r_literal(sub('^tests/testthat/', '', spec$contracts_file)),
        '))[[',
        r_literal(operation$name),
        ']]'
      ),
      if (length(contract$environment)) {
        '  withr::local_envvar(unlist(contract$environment, use.names = TRUE))'
      },
      '  captured <- list()',
      '  mock_for <- function(name) {',
      '    force(name)',
      '    function(...) {',
      '      position <- length(captured) + 1L',
      '      captured[[position]] <<- list(helper = name, arguments = list(...))',
      '      if (position > length(contract$calls)) stop("Unexpected extra helper call")',
      '      contract$calls[[position]]$response',
      '    }',
      '  }',
      paste0(
        '  testthat::local_mocked_bindings(',
        paste(
          vapply(
            helpers,
            function(name) paste0(name, ' = mock_for(', r_literal(name), ')'),
            character(1)
          ),
          collapse = ', '
        ),
        ', .package = ',
        r_literal(spec$package),
        ')'
      ),
      paste0(
        '  result <- do.call(',
        spec$package,
        '::',
        operation$name,
        ', contract$inputs)'
      ),
      "  testthat::expect_identical(captured, lapply(contract$calls, function(x) x[c('helper', 'arguments')]))",
      '  testthat::expect_identical(result, contract$result)',
      '})'
    ),
    collapse = '\n'
  )
}
