render_contract <- function(operation, spec, contract) {
  if (
    !all(c('inputs', 'request', 'result') %in% names(contract)) ||
      !'response_fixture' %in% union(names(spec), names(contract))
  ) {
    stop('Supply fixed contract inputs, request, result and response_fixture')
  }
  stopifnot(identical(make.names(spec$package), spec$package))
  args <- paste(
    vapply(
      names(contract$inputs),
      function(name) {
        paste0(
          r_literal(make.names(name)),
          ' = ',
          r_literal(contract$inputs[[name]])
        )
      },
      character(1)
    ),
    collapse = ', '
  )
  paste(
    c(
      '# Generated by wrapmaint; do not edit by hand.',
      paste0(
        'testthat::test_that(',
        r_literal(paste(
          operation$name,
          'completes the fixed request contract'
        )),
        ', {'
      ),
      '  captured <- NULL',
      '  calls <- 0L',
      paste0(
        '  mock <- function(...) { calls <<- calls + 1L; captured <<- list(...); ',
        r_literal(
          if ('response_fixture' %in% names(contract)) {
            contract$response_fixture
          } else {
            spec$response_fixture
          }
        ),
        ' }'
      ),
      paste0(
        '  testthat::local_mocked_bindings(',
        spec$helper,
        ' = mock, .package = ',
        r_literal(spec$package),
        ')'
      ),
      paste0(
        '  result <- ',
        spec$package,
        '::',
        operation$name,
        '(',
        args,
        ')'
      ),
      paste0(
        '  testthat::expect_identical(captured, ',
        r_literal(contract$request),
        ')'
      ),
      '  testthat::expect_identical(calls, 1L)',
      paste0(
        '  testthat::expect_identical(result, ',
        r_literal(contract$result),
        ')'
      ),
      '})'
    ),
    collapse = '\n'
  )
}
