render_contract <- function(operation, spec, contract) {
  if (
    is.null(contract$inputs) ||
      is.null(contract$request) ||
      is.null(contract$result) ||
      is.null(spec$response_fixture)
  ) {
    stop('Supply fixed contract inputs, request, result and response_fixture')
  }
  stopifnot(identical(make.names(spec$package), spec$package))
  args <- paste(
    vapply(
      names(contract$inputs),
      function(name) {
        paste0(
          r_literal(make.names(name)),
          ' = ',
          r_literal(contract$inputs[[name]])
        )
      },
      character(1)
    ),
    collapse = ', '
  )
  paste(
    c(
      '# Generated by wrapmaint; do not edit by hand.',
      paste0(
        'testthat::test_that(',
        r_literal(paste(
          operation$name,
          'completes the fixed request contract'
        )),
        ', {'
      ),
      '  captured <- NULL',
      paste0(
        '  mock <- function(...) { captured <<- list(...); ',
        r_literal(spec$response_fixture),
        ' }'
      ),
      paste0(
        '  testthat::local_mocked_bindings(',
        spec$helper,
        ' = mock, .package = ',
        r_literal(spec$package),
        ')'
      ),
      paste0(
        '  result <- ',
        spec$package,
        '::',
        operation$name,
        '(',
        args,
        ')'
      ),
      paste0(
        '  testthat::expect_identical(captured, ',
        r_literal(contract$request),
        ')'
      ),
      paste0(
        '  testthat::expect_identical(result, ',
        r_literal(contract$result),
        ')'
      ),
      '})'
    ),
    collapse = '\n'
  )
}
